# Terraform version and provider requirements are generated by Terragrunt
# See root terragrunt.hcl for generate block

provider "aws" {
  region = var.aws_region
}

provider "vault" {
  address = var.vault_address

  auth_login {
    path = "auth/approle/login"
    parameters = {
      role_id   = var.vault_role_id
      secret_id = var.vault_secret_id
    }
  }
}

# Backend configuration is managed by Terragrunt
terraform {
  backend "s3" {}
}

